# Generated by Django 3.1.2 on 2020-10-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201005_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_favourite', to='api.application')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_app', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userfavouritegames',
            name='game',
        ),
        migrations.RemoveField(
            model_name='userfavouritegames',
            name='user',
        ),
        migrations.RenameModel(
            old_name='GameCategory',
            new_name='Feature',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='UserFavouriteGames',
        ),
        migrations.AddField(
            model_name='favouritefeatures',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_favourite', to='api.feature'),
        ),
        migrations.AddField(
            model_name='favouritefeatures',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_features', to='api.userprofile'),
        ),
    ]
