# Generated by Django 3.1.2 on 2020-10-06 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201006_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteapps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_app', to='api.userprofile'),
        ),
    ]
