# Generated by Django 3.1.2 on 2020-10-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201006_0707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteApps',
            new_name='TopApps',
        ),
        migrations.RenameModel(
            old_name='FavouriteFeatures',
            new_name='TopFeatures',
        ),
    ]
