# Generated by Django 3.1.2 on 2020-10-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201006_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topapps',
            old_name='applications',
            new_name='application',
        ),
    ]
