# Generated by Django 3.1.2 on 2020-10-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201006_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topfeatures',
            name='features',
        ),
        migrations.AddField(
            model_name='topfeatures',
            name='feature',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='feature_top', to='api.feature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topfeatures',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_top', to='api.userprofile'),
        ),
    ]
